name: Epitech Mirroring

on:
  push:
    branches:
      - "main"
      - "release-**"

jobs:
  synchronize-repository:
    name: Synchronize Repository
    if: github.repository == vars.CURRENT_REPO && github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Checking out repository...
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Synchronizing repository to mirror...
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ vars.MIRROR_URL }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}

      - name: Synchronize wiki to mirror...
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ vars.MIRROR_WIKI }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
